on: [push]

jobs:
  test-action:
    runs-on: ubuntu-latest
    name: Testing action
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Get Last Check Artifact
      uses: actions/download-artifact@v2
      with:
        name: last_check
    - name: Check commits in remote repo
      uses: ./
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        owner: sveltejs
        repo: kit
        dir: documentation
        days: 3
    - name: 'Save Last Check Artifact'
      uses: actions/upload-artifact@v2
      with:
        name: last_check
        path: .last_check
