on: [push]

jobs:
  test-action:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: Check commits in remote repo
      uses: ./
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        owner: 'sveltejs'
        repo: 'kit'
        dir: 'documentation'
        days: 3
